const LANG = {
	id: { 
		btnTarget: "📚 Target Pembuatan Tome", 
		title2: "📋 Rincian Crafting Tome", 
		title3: "💰 Estimasi Biaya Pasar", 
		title4: "📦 Inventory", 
		desc3: "Masukkan harga pasar per item untuk mengestimasi Gold yang dibutuhkan.", 
		desc4: "Item ini secara otomatis akan mengurangi total kebutuhan", 
		progText: "Progres Pengumpulan:", 
		btnCalc: "Hitung Kuantitas", 
		totalCostLabel: "Total Sisa Biaya:", 
		btnReset: "🔄 Reset Kalkulator", 
		searchPlaceholder: "🔍 Cari nama tome...", 
		modalTitleAdd: "Simpan ke Inventaris", 
		modalDesc: "Berapa banyak item yang Anda inginkan?", 
		btnSave: "Simpan", 
		btnCancel: "Batal", 
		baseMat: "Bahan Dasar", 
		lvl: "Level", 
		alertReset: "Hapus semua perhitungan dan mulai dari awal di Cloud?", 
		statEquipDesc: "* Mengikat saat digunakan (Bind on Equip).", 
		footerText: "Kalkulator Tome © 2026 | Dibuat oleh <strong>Sulfikar</strong>", 
		matDesc: "Bahan Crafting",
		btnAddItem: "➕ Tambah Item",
		modalInvTitle: "Menambahkan Item",
		invSearchPlaceholder: "🔍 Cari nama tome/bahan...",
		btnCloseWindow: "Tutup Jendela",
		btnCopy: "Salin Daftar Belanja",
		btnCompact: "Toggle Mode Ringkas",
		btnFav: "Simpan sebagai Favorit",
		btnLoadFav: "Muat Favorit Tersimpan",
		msgCopyOk: "Daftar belanja berhasil disalin ke clipboard!",
		msgFavSave: "Target ini telah disimpan sebagai favorit!",
		msgFavDel: "Favorit dihapus.",
		msgNoFav: "Belum ada favorit yang tersimpan.",
		txtTarget: "Target",
		txtMissing: "Sisa bahan dibutuhkan",
		txtComplete: "Tidak ada (Sudah Lengkap)",
		btnReverse: "🔍 Analisis Potensi",
		modalRevTitle: "🔍 Analisis Potensi Crafting",
		modalRevDesc: "Sistem mendeteksi isi Inventory Anda dan menghitung Tome terbaik yang bisa dibuat.",
		txtReadyToCraft: "✅ SIAP DIRAKIT (100% LENGKAP)",
		txtNearbyCraft: "⚡ HAMPIR SELESAI (TOP PROGRES)",
		txtNoMats: "Inventory Anda kosong. Tambahkan beberapa bahan atau Tome terlebih dahulu!",
		txtSelectTarget: "Jadikan Target",
		farmTitle: "Optimalisasi Farm",
		farmComplete: "✅ Semua material atau Token mencukupi untuk Crafting!",
		farmBuy: "🛒 Beli di Item Mall/Farming:",
		farmRecToken: "Gunakan <strong>{tokens} Token of Luck</strong> untuk mencetak <strong>{pages} Tome Page</strong>.",
		chatTitle: "Chat Global",
		chatDesc: "Tempat berkumpul dan koordinasi semua Player secara real-time!",
		chatPlaceholder: "Ketik pesan di sini (Enter untuk kirim)...",
		navTarget: "Target",
		navCraft: "Crafting",
		navInv: "Inventory",
		navCost: "Biaya",
		navChat: "Chat"
	},
	en: { 
		btnTarget: "📚 Target Tome Crafting", 
		title2: "📋 Tome Crafting Details", 
		title3: "💰 Market Cost Estimator", 
		title4: "📦 Inventory", 
		desc3: "Enter the market price per item to estimate required Gold.", 
		desc4: "Items here will automatically deduct from total requirements.", 
		progText: "Collection Progress:", 
		btnCalc: "Calculate Qty", 
		totalCostLabel: "Total Remaining Cost:", 
		btnReset: "🔄 Reset Calculator", 
		searchPlaceholder: "🔍 Search target book name...", 
		modalTitleAdd: "Add to Inventory", 
		modalDesc: "How many items do you want?", 
		btnSave: "Save", 
		btnCancel: "Cancel", 
		baseMat: "Base Materials", 
		lvl: "Level", 
		alertReset: "Clear all calculations and start over from Cloud?", 
		statEquipDesc: "* Bind on Equip.", 
		footerText: "Tome Calculator © 2026 | Created by <strong>Sulfikar</strong>", 
		matDesc: "Crafting Material",
		btnAddItem: "➕ Add Item",
		modalInvTitle: "Select Item for Inventory",
		invSearchPlaceholder: "🔍 Search book or material name...",
		btnCloseWindow: "Close Window",
		btnCopy: "Copy Shopping List",
		btnCompact: "Toggle Compact Mode",
		btnFav: "Save as Favorite",
		btnLoadFav: "Load Saved Favorite",
		msgCopyOk: "Shopping list copied to clipboard!",
		msgFavSave: "Target saved as favorite!",
		msgFavDel: "Favorite removed.",
		msgNoFav: "No favorite saved yet.",
		txtTarget: "Target",
		txtMissing: "Remaining materials needed",
		txtComplete: "None (Complete)",
		btnReverse: "🔍 Analyze Potential",
		modalRevTitle: "🔍 Crafting Potential Analysis",
		modalRevDesc: "The system scans your Inventory and calculates the best Tomes you can create.",
		txtReadyToCraft: "✅ READY TO CRAFT (100% COMPLETE)",
		txtNearbyCraft: "⚡ NEARBY COMPLETION (TOP PROGRESS)",
		txtNoMats: "Your inventory is empty. Please add some materials or Tomes first!",
		txtSelectTarget: "Set as Target",
		farmTitle: "Smart Farming Optimizer",
		farmComplete: "✅ All materials or Tokens are sufficient for Crafting!",
		farmBuy: "🛒 Buy from Item Mall:",
		farmRecToken: "Use <strong>{tokens} Token of Luck</strong> to forge <strong>{pages} Tome Page</strong>.",
		chatTitle: "Global Chat",
		chatDesc: "Real-time gathering and coordination room for all players!",
		chatPlaceholder: "Type a message here (Enter to send)...",
		navTarget: "Target",
		navCraft: "Crafting",
		navInv: "Inventory",
		navCost: "Cost",
		navChat: "Chat"
	}
};